#[build]
#  command = "npm run build"  # Comando para construir el cliente (ajusta según tu configuración)
#  functions = "./server"  # Ruta a la carpeta del servidor

[build]
  base = "client/"
  publish = "client/dist/"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  directory = "server/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
    cache-control = "max-age=0, no-cache, no-store, must-revalidate"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "client/dist/"
