[build]
  command = "cd cliente && npm install && npm run build"
  publish = "cliente/dist"

[[redirects]]
  from = "/api/*"
  to = "/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/cliente/:splat"
  status = 200
