[build]
  command = "cd client && npm install && npm run dev"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/client/:splat"
  status = 200