[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/client/:splat"
  status = 200